name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  bats:
    name: bats test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

      - name: Setup Bats
        uses: bats-core/bats-action@5b1e60c2ee94cb1b44a616ea4b1f466f9d6e38ef  # 4.0.0
        with:
          support-install: false
          assert-install: false
          detik-install: false
          file-install: false

      - name: Install ripgrep
        run: sudo apt-get install -y ripgrep

      - name: Run tests
        run: bats test/kubectl-mns.bats
